### ISSUE TITLE
serialized name annotation

### ISSUE THREAD

**Issue by y9san9** [papsign/Ktor-OpenAPI-Generator#47]
![image](https://user-images.githubusercontent.com/46930374/82045261-75566800-96b7-11ea-9725-a77e68f53485.png)
Is there possibility to rename parameters as in Gson library ?
![image](https://user-images.githubusercontent.com/46930374/82045324-94ed9080-96b7-11ea-893a-ad6609ac80e5.png)
I want generate parameters with different name in Kotlin and Json

**Comment by Wicpar** [comment]
I'll see if you can add it as a module or not, if not i'll try to add functionality to allow the handling of such cases.

**Comment by y9san9** [comment]
Okey, waiting for reply

**Comment by y9san9** [comment]
Maybe I can use Gson serializer instead of Jackson ?

**Comment by Wicpar** [comment]
you can use replaceModule in the config, and replace this default module
https://github.com/papsign/Ktor-OpenAPI-Generator/blob/master/src/main/kotlin/com/papsign/ktor/openapigen/schema/builder/provider/DefaultObjectSchemaProvider.kt
with one that takes in account the name from the annotation, this is the relevant part:
```kotlin
SchemaModel.SchemaModelObj<Any?>(
    props.associate {
        // change name here if it is annotated
        Pair(it.name, builder.build(it.type, it.source.annotations))
    },
    props.filter {
        !it.type.isMarkedNullable
    }.map { it.name } // make sure to have the right name here as well
)
```
in the config:
```kotlin
replaceModule(DefaultObjectSchemaProvider, CustomObjectSchemaProvider)
```

Allowing a more generic modification requires quite a bit more work, probably a system like the validators but the module detects the annotation instead of the other way around.

If you want such an extension system feel free to open another issue.

**Comment by y9san9** [comment]
should I extend my class from it? It is final type as I see

**Comment by Wicpar** [comment]
no, you create a new one, and replace the default module with yours using replaceModule in the config.

**Comment by y9san9** [comment]
Can I do same with headers ?
I wanna name header 'token' in Kotlin and 'Authorization' in request (without Auth)

**Comment by Wicpar** [comment]
Yes normally you should be able to, look which module instanciates the header's model.
All openapi structures are defined in the models package, it should be 1:1 to the spec, look what module instanciates the model you wish to customize, and replace the module with a custom one.

**Comment by y9san9** [comment]
Ok thanks
