### ISSUE TITLE
Support for model parameter descriptions

### ISSUE THREAD

**Issue by bherbst** [papsign/Ktor-OpenAPI-Generator#52]
I would love to be able to annotate model properties with descriptions, like we can do with `@HeaderParam`, `@PathParam`, and `@QueryParam`, and it doesn't look like that is currently possible.

I'd imagine something like the new `@OpenAPIName` would work well.

**Comment by Wicpar** [comment]
I won' t be able to implement anything of that kind until the week after the next,
but if you want to take a shot at it you can:
1. Add the description property to the schemaModel https://github.com/papsign/Ktor-OpenAPI-Generator/blob/master/src/main/kotlin/com/papsign/ktor/openapigen/model/schema/SchemaModel.kt
2. Create a validator to edit the properties you want (validators are type annotations, look at `@Min`, `@Max`, `@Clamp` and how they are implemented)

OpenAPIName was a special case because it changed serialization/deserialization behavior.

**Comment by Wicpar** [comment]
Thank you for the contributions :), merged and released.
